### ISSUE TITLE
Create extension that adds a Honeypot type of Captcha to the Join and Contact forms.

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-honeypot#1]
Nova has no method of spam bot protection built-in. Create an extension that adds a honeypot to the Contact and Join forms.

Honeypot info: https://www.thryv.com/blog/honeypot-technique/

Contact Page: https://novadev.game-hosting.org/index.php/main/contact
Join Page: https://novadev.game-hosting.org/index.php/main/join

**Comment by pawanmall157** [comment]
done

**Comment by reecesavage** [comment]
![image](https://user-images.githubusercontent.com/15860882/108806197-a331dc80-7566-11eb-91e8-d396f6621028.png)
The contact page looks good.
Join page honeypot fields aren't added correctly.

**Comment by reecesavage** [comment]
confirmed fixed
