### ISSUE TITLE
message sends even with text in the Honeypot fields

### ISSUE THREAD

**Issue by reecesavage** [reecesavage/nova-ext-honeypot#3]
Using inspector I removed the hidden: true; styling and entered a value in Last Name. The form still emailed.

![image](https://user-images.githubusercontent.com/15860882/108907611-ec764080-75e7-11eb-9d81-1612436ee7bd.png)

**Comment by pawanmall157** [comment]
fixed

**Comment by reecesavage** [comment]
confirmed fixed
